### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [gaborbata/jpass#11]
Hi good day! Im Jibbie Eguna, a graphics designer, I would like to ask for your permission to propose a new designs of logo in your application/project. I would like to help projects in open-source .I would just like to propose new designs if you are needing it. Hoping for your positive response Thank You!

**Comment by gaborbata** [comment]
Hi @jbeguna04, feel free to propose new logo/designs for JPass. Thanks, Gabor

**Comment by jbeguna04** [comment]
Thank you for your response. Ill be making a presentation about the designs afterwards

**Comment by jbeguna04** [comment]
Thank you for waiting, Any suggestions regarding the logo is always accepted.
![image](https://user-images.githubusercontent.com/35353768/40953932-a831cb62-68b4-11e8-8e78-f33e54c6ee06.png)

**Comment by gaborbata** [comment]
@jbeguna04 it looks awesome. I think it could be applied to:
* the github readme page
* application icon (instead of the current yellow lock currently shown on the taskbar) -- however we have to make sure the logo looks good on very low resolution as well
* about page of JPass

**Comment by jbeguna04** [comment]
Thank you for your response. Ill send a pull request containing all files that you can use

**Comment by gaborbata** [comment]
Thanks @jbeguna04 for your work. I'll review and merge the PR soon (https://github.com/gaborbata/jpass/pull/12)
