### ISSUE TITLE
Open File Dialog in the actual Directory

### ISSUE THREAD

**Issue by ulipillepalle** [gaborbata/jpass#13]
diff --git a/src/main/java/jpass/ui/action/MenuActionType.java b/src/main/java/jpass/ui/action/MenuActionType.java
index 4b1b3e9..f1e9e66 100644
--- a/src/main/java/jpass/ui/action/MenuActionType.java
+++ b/src/main/java/jpass/ui/action/MenuActionType.java
@@ -73,7 +73,7 @@
 
         @Override
         public void actionPerformed(ActionEvent ev) {
-            openFile(JPassFrame.getInstance());
+            openFile(JPassFrame.getInstance("."));
         }
     }),
     SAVE_FILE(new AbstractMenuAction("Save", getIcon("save"), getKeyStroke(KeyEvent.VK_S, CTRL_MASK)) {

**Comment by gaborbata** [comment]
This behavior is currently working as designed. Could you please create a configuration entry for that in `jpass.properties`?

**Comment by gaborbata** [comment]
Closing as per https://github.com/gaborbata/jpass/releases/tag/v0.1.27
