### ISSUE TITLE
Store the date of last modification of an entry

### ISSUE THREAD

**Issue by sebkirche** [gaborbata/jpass#15]
Hi, and many thanks for your work that I use almost every day.

Would you mind to add a property to the entries to store the date of creation / last modification of a password? (Note that if you are OK, I might propose a code change, albeit I am a bit rusty with swing)

**Comment by gaborbata** [comment]
Hi @sebkirche,

Very good idea, feel free to contribute.
Regarding Swing I'm in the same rusty shoe. 😄 

Thanks,
Gabor

**Comment by AndreaRe9** [comment]
Hi  @sebkirche,
Is this the modification you were proposing?

<img width="402" alt="scr" src="https://user-images.githubusercontent.com/59319678/88558913-7814f800-d02c-11ea-8a26-681fa03bac94.png" >

**Comment by gaborbata** [comment]
I'm closing this ticket as https://github.com/gaborbata/jpass/pull/17 has been merged.
