### ISSUE TITLE
modification of .jpass is possible by anyone...

### ISSUE THREAD

**Issue by D-e-n-i-s-h** [gaborbata/jpass#16]
Anybody can modify the file where the password is saved.
As result we lost our data.

**Comment by CatPlanet** [comment]
And?

**Comment by D-e-n-i-s-h** [comment]
so i was asking is there a way that we can  allow editing of file only when we are in jpass app.And when we open (.jpass) file outside in normal environment it should just open in read only mode.

**Comment by gaborbata** [comment]
@D-e-n-i-s-h if I understand that right, you are talking about the read-only attribute on `.jpass` files. 

Currently, JPass does not support that feature, however it is possible to add support to set read-only flag when a `.jpass` file is loaded/saved.

In my opinion, read-only flag does not provide too much protection against deletion or modification as it is quite easy to change. Instead, you may have to set proper user permissions to your specific `.jpass` file to protect against other users to modify your file.
