### ISSUE TITLE
Cannot process document (Not in GZIP format)

### ISSUE THREAD

**Issue by kubow** [gaborbata/jpass#23]
Hello,
looks like my password db got corrupted somehow (not sure how though) and I cannot open it anymore.
Dummy me, I should have made a backup after the last change (it was just a password regeneration, but will be hard to reset again without the last one).
Is it possible to revive this file somehow? 
Thanks!

![image](https://user-images.githubusercontent.com/6998388/134206230-3bf76316-c916-4ec8-b117-c13baa27749c.png)

EDIT: I reverted back to previous version of my password db and I have the same problem. So the issue is happening on the application level.

**Comment by kubow** [comment]
😄 even dummier me 😄 
that is just a message for a bad password typed in....
Right password opens it, it seems just a bad day for working on PC, you can close this issue.
Maybe plan some relevant message to pop-up for dummy people like me.
Thanks for brilliant software, use it everyday!

**Comment by gaborbata** [comment]
This must be addressed in https://github.com/gaborbata/jpass/releases/tag/v0.1.29
