### ISSUE TITLE
Multilanguage interface

### ISSUE THREAD

**Issue by bovirus** [gaborbata/jpass#29]
@gaborbata 

Could you please consdier to modify sorurce code to have multilanguage interface?

Is it possible to use external file for list of strings?

Is it possible to use your program to open an URL and fillin user/password?

**Comment by gaborbata** [comment]
Hi @bovirus, thanks for your suggestions. I have no engineering capacity to implement them at the moment, but feel free to contribute.

**Comment by bovirus** [comment]
@gaborbata 

What's the file to translate to add ex Italian language strings?

**Comment by gaborbata** [comment]
Hey @bovirus you can use [languages_en_US.properties](https://github.com/gaborbata/jpass/blob/master/src/main/resources/resources/languages/languages_en_US.properties).
