### ISSUE TITLE
Possible contribution

### ISSUE THREAD

**Issue by GioAgu17** [gaborbata/jpass#5]
Hello!

I am Giovanni, a student from University of Illinois at Chicago and I just cloned your repo for doing a homework with your application! 

Since I created an sbt script in order to build and run the application and all the tests, I would like to know whether I could contribute to this repo with this script. Also, I've tested a class that wasn't covered. 

Let me know!
Thank you,
Giovanni

**Comment by gaborbata** [comment]
Hi Giovanni,

Yes, any contribution is welcome. Feel free to open a pull request with your changes.

Thanks,
Gabor

**Comment by gaborbata** [comment]
I'm closing this issue as the PR (https://github.com/gaborbata/jpass/pull/6) has been created.
